# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cba886279114c8fba826370d72a618f0b878c83556069400d06a6efcb422316de6dd1f5dc491e9ca46fd3f0b92daa7144b9b4e92991cc3a518ef6b5a0624591

test:
  secret_key_base: fdf1edd165a0f4ffcd0d4d7f988d9ebebda31b348867d803134e1b1a06e81f131201ca57d1f7b3e1e1b1b5cc2406351976018f549cbb3c8a40411750a830202f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
